export default function Head() {
  return (
    <>
      <title>Lanas - Webdesign</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by Supabase Gumroad clone" />
      <meta charSet="utf-8" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
