/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Karol Miklas (https://sketchfab.com/karolmiklas)
license: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
source: https://sketchfab.com/3d-models/free-merc-hovercar-oFfjKlslHqXgtKdKqEtpffmSv6h
title: (FREE) Merc Hovercar
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/merc.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0.02, 0.05, -0.07]} scale={1}>
          <mesh geometry={nodes.Plane006_0.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Plane006_1.geometry} material={materials.Material_light} />
          <group position={[0, 0, -0.58]} scale={[1.19, 2, 1]}>
            <mesh geometry={nodes.Plane_0.geometry} material={materials.Plane_0} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/merc.gltf')
